
DOME_DIA = 51.2;
DOME_THICK = 2.5;
SEAL_MARGIN = 0.8;
PROP_SHROUD_DIA = 50;
PROP_SHROUD_THICK = 2.5;
SHELL_MARGIN = 0.4;
SHELL_THICK= 1.6;
SKREW_INNER_DIA = 23.3;
SKREW_OUTER_DIA = 26.5;
CHAMBER_DIA = 100;
LED_ENABLED = false;

function r_from_dia(d) = d / 2;